version: '3.8'

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ecommerce-network

  # Future services will be added here
  # product-service:
  #   build: ./services/product-service
  #   ports:
  #     - "8081:8080"
  
  # mysql-db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: ecommerce
  #   ports:
  #     - "3306:3306"

networks:
  ecommerce-network:
    driver: bridge
